Repository github/india, pull requests merged in 2022-09, with the labels that each got.

#905 chore: (projects): Add doggo
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#907 Add CircuitVerse to the projects list
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#908 Update maintainers.yml
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#909 Update maintainers.yml
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#911 Update maintainers.yml
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#917 Add "Nikhil-Ladha" to maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#919 feat: include rumqtt
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#927 Update state in maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#930 Add Ockam to Open Source projects list
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#942 Added LitmusChaos project
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#934 update maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#912 projects.yml: add box-cli-maker project
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#939 Adding SAML Jackson from BoxyHQ
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#943 DevOps Community added and maintainer too
  website/data/open-source/maintainers.yml
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#937 Adding Harminder Virk (myself)
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#935 Add amitmerchant1990
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#941 [Projects] Add Meshery to Open source projects list
  website/data/open-source/projects.yml
Labels: githubindia.com, valid, change-requested

#948 Add winkNLP to project list
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#951 Update projects.yml to add Testing Category
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#933 Add privado project & maintainer
  website/data/open-source/maintainers.yml
  website/data/open-source/projects.yml
Labels: githubindia.com, valid, change-requested

#940 added Activeloopai/Hub to the list of DS projects
  website/data/open-source/projects.yml
Labels: question, githubindia.com, valid

#953 Add nikochiko to maintainers, autosaved to projects
  website/data/open-source/maintainers.yml
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#952 Add ReactPlay To Projects list
  website/data/open-source/projects.yml
Labels: question, githubindia.com, valid

#954 adding anantshri to maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#955 Add `one-aalam` to maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#959 Added the project Face-X and updated the maintainers.yml
  website/data/open-source/maintainers.yml
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#956 added karate to projects from india
  website/data/open-source/projects.yml
Labels: githubindia.com, valid

#962 Adding 0xinfection to the maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#963 Add blenderskool as maintainer from Karnataka
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#965 Adding s0md3v to the maintainers list
  website/data/open-source/maintainers.yml
Labels: githubindia.com, valid

#960 add: awesome-github-profile-readme:
  website/data/open-source/maintainers.yml
  website/data/open-source/projects.yml
Labels: githubindia.com, valid
